# Generated by Django 4.0.5 on 2022-06-16 21:18

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7, verbose_name='Nome')),
                ('img', stdimage.models.StdImageField(force_min_size=False, upload_to='types', variations={'tumb': {'crop': True, 'height': 500, 'width': 300}})),
            ],
        ),
    ]
