# Generated by Django 4.0.5 on 2022-06-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Type'},
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=8, verbose_name='Nome'),
        ),
    ]
