# Generated by Django 4.0.5 on 2022-06-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_types_options_alter_types_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Types',
        ),
    ]
